### ISSUE TITLE
Start time and raw time limit cannot be parsed if its "partitionlimit" or None

### ISSUE THREAD

**Issue by jcklie** [neilmunday/slurm-mail#58]
**Versions**

OS version: Centos 7
Slurm version: 22.05.02
Slurm Mail version: 4.1

**Describe the bug**

I see the following in my slurm mail log:

```
2022/11/01 14:14:01:INFO: processing: /var/spool/slurm-mail/31114_1667303920.1738784.mail
2022/11/01 14:14:01:WARNING: job 31114: could not parse 'None' for job start timestamp
2022/11/01 14:14:01:ERROR: Failed to process: /var/spool/slurm-mail/31114_1667303920.1738784.mail
2022/11/01 14:14:01:ERROR: invalid literal for int() with base 10: 'Partition_Limit'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/slurmmail/cli.py", line 587, in send_mail_main
    __process_spool_file(f, smtp_conn, options)
  File "/usr/lib/python3.6/site-packages/slurmmail/cli.py", line 227, in __process_spool_file
    job.wallclock = int(sacct_dict['TimelimitRaw']) * 60
ValueError: invalid literal for int() with base 10: 'Partition_Limit'
```
Looking at the sacct output, I see

```
[root@wormulon slurm-mail]# sacct -j 31114 -P -n --fields=JobId,User,Group,Partition,Start,End,State,ReqMem,MaxRSS,NCPUS,TotalCPU,NNodes,WorkDir,Elapsed,ExitCode,Comment,Cluster,NodeList,TimeLimit,TimelimitRaw,JobIdRaw,JobName

31114|XXX|domänen-benutzer|yolo|None|2022-11-01T12:58:39|CANCELLED by 1060117917|32G||2|00:00:00|1|/mnt/beegfs/work/XXX/HGN/XYZ/HGN|00:00:00|0:0||ukp-cluster|None assigned|Partition_Limit|Partition_Limit|31114|multimodal_gated

```

It looks like it is an edge case for a job canceled by user, start timestamp and time limit are not guaranteed to be ints it seems?

**Comment by neilmunday** [comment]
I've been trying to recreate this issue without success.

It's interesting that the job's start time is `None` yet the end time is `2022-11-01T12:58:39`.

I'll look into adding some better handling of `sacct` output.

**Comment by jcklie** [comment]
Thanks! It was by a user and I just saw the errors in the log, so I experienced it second hand only.

**Comment by neilmunday** [comment]
Issue resolved.
